import Head from 'next/head';
import { Typography, Button, Auth } from '@supabase/ui';
import { useContext } from 'react';
import { SupabaseContext } from '../components';

export default function Home() {
  const { user } = Auth.useUser();
  const supabaseClient = useContext(SupabaseContext);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography.Text>Signed in: {user.email}</Typography.Text>

        <Button block onClick={() => supabaseClient.auth.signOut()}>
          Sign out
        </Button>
      </main>
    </div>
  );
}
